### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Cbiswadeep** [joaromi/Spiking-RetinaNet#1]
Hey! While running the code on the jupyter notebook, I am getting the following error: 

.
.
.
Parsing layer Conv2D.
Parsing layer Conv2D.
Parsing layer Conv2D.
Parsing layer UpSampling2D.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-26-4aadd3f06670> in <module>
     22 print('FPN input layers = ', [layer.name for layer in FPN_in])
     23 print('FPN output layers = ', [layer.name for layer in FPN_out], '\n')
---> 24 idx,FPN_tails = model_parser.parse_subnet(subnet, idx, prev_out_idx=bbone_tails, in_layers=FPN_in, out_layers = FPN_out, repair=[subnet[-1]], special_relu=[subnet[-2]])
     25 print(idx, ' - ', FPN_tails)
     26 

~/github/Spiking-RetinaNet/snntoolbox/parsing/utils.py in parse_subnet(self, layers, idx, prev_out_idx, in_layers, out_layers, repair, special_relu)
    252                     inbound = [self._layer_list[-1]['name']]
    253                 else:
--> 254                     inbound = self.get_inbound_names(layer, name_map)
    255             else:
    256                 inbound = []

~/github/Spiking-RetinaNet/snntoolbox/parsing/utils.py in get_inbound_names(self, layer, name_map)
    648         """
    649 
--> 650         inbound = self.get_inbound_layers(layer)
    651         for ib in range(len(inbound)):
    652             for _ in range(len(self.layers_to_skip)):

~/github/Spiking-RetinaNet/snntoolbox/parsing/model_libs/keras_input_lib.py in get_inbound_layers(self, layer)
     39 
     40     def get_inbound_layers(self, layer):
---> 41         return get_inbound_layers(layer)
     42 
     43     @property

~/github/Spiking-RetinaNet/snntoolbox/parsing/utils.py in get_inbound_layers(layer)
   1388     try:
   1389         # noinspection PyProtectedMember
-> 1390         inbound_layers = layer._inbound_nodes[0].inbound_layers
   1391     except AttributeError:  # For Keras backward-compatibility.
   1392         inbound_layers = layer.inbound_nodes[0].inbound_layers

IndexError: list index out of range

**Comment by joaromi** [comment]
Sorry the code is not fully uploaded yet. It will be functional within the next few weeks.

**Comment by Cbiswadeep** [comment]
Oh, sure no problem! Thanks a lot for sharing the code!

**Comment by Cbiswadeep** [comment]
Hey! Is this the final version as it is still giving the same issue? I feel there are some additional objects in the SNNToolbox for the Upsampling and NormAdd which are not there in the current implementation.

**Comment by joaromi** [comment]
Hi, nothing should be missing now. Have you checked whether you are using a compatible TF/keras version? The ones I used are specified in the Readme file. 

It looks like the initial RetinaNet network is being generated with a slightly different structure and one of the layers in the FPN is not pulling through the parsing.

**Comment by Cbiswadeep** [comment]
Yes I checked the tensorflow and keras versions. It is still giving me the same errors. I feel the problem is the snntoolbox you shared is not the updated one which can parse the upsampling layers and the normadd layers.
